ansible-k8s-vsphere/tasks/main.yml, ansible-k8s-vsphere/templates/cluster.j2, ansible-k8s-vsphere/templates/ova_spec.j2, ansible-k8s-vsphere/templates/user-data.j2
- Added ansible tasks to create a k8s cluster using RKE on vSphere.
=> ✨🤖 add ansible tasks to create a k8s cluster on vsphere

.gitignore, terraform/1_k8s_cluster_setup/.terraform.lock.hcl, terraform/1_k8s_cluster_setup/azurerm.tf, terraform/1_k8s_cluster_setup/external-dns.tf, terraform/1_k8s_cluster_setup/providers.tf, terraform/1_k8s_cluster_setup/variables.tf, terraform/configurations/acmapp_prod.tfvars
- Adds the ExternalDNS helm chart.
- Creates Azure Service Principal and role attachments.
- Creates k8s secrets for ExternalDNS to use.
=> ✍️☸️Adding ExternalDNS to Kubernetes Cluster

azure/terraform/stacks/acm-general/dns.tf
Reverts acm-uic/IaC#16
This reverts the demo entry that was made in our DNS zone.
=> Revert "Adding a test demo record"

.github/workflows/azure_terraform_apply.yml, .github/workflows/azure_terraform_plan.yml, azure/terraform/stacks/acm-general/.terraform.lock.hcl, azure/terraform/stacks/acm-general/providers.tf, azure/terraform/stacks/acm-general/service_principal.tf
This creates an Active Directory Service Principal for use in the SIGSysAdmin Demo.
This will be a short-lived token.
=> Creating new service account for SIGSysAdmin Demo

azure/terraform/stacks/acm-general/service_principal.tf
Fixing role assignment to actually use the demo account.
=> Correcting role assignment to use demo service account

.github/workflows/kubelint.yml
- Add linter for YAMLs
- Do we need a linter config?
=> 🔍 Add kube linter for PRs.

kubernetes/argocd/stacks/sysadmindemo/turducken.yml
Plz merge senpai chase thanks uwu
=> 🐔 Cluck cluck

kubernetes/argocd/stacks/common/plausible.yml, kubernetes/argocd/stacks/plausible/clickhouse.yml, kubernetes/argocd/stacks/plausible/plausible.yml, kubernetes/argocd/stacks/plausible/postgres.yml, kubernetes/argocd/stacks/plausible/smtp.yml
Add kubernetes manifests to run plausible analytics and services that it depends on (clickhouse, postgres)
=> Add plausible kubernetes stack

kubernetes/argocd/stacks/common/radius.yml, kubernetes/argocd/stacks/radius/Dockerfile, kubernetes/argocd/stacks/radius/assets/supervisord.conf, kubernetes/argocd/stacks/radius/configmap.yml, kubernetes/argocd/stacks/radius/docker-entrypoint.sh, kubernetes/argocd/stacks/radius/radius.yml
Add manifests to run freeradius
=> ✨ freeradius service

kubernetes/argocd/stacks/common/projects.yml
re-create infrastructure project. it was removed during a bad rebase for #66
=> 🚑 bring back infrastructure project

azure/terraform/stacks/acm-general/container_registry.tf, azure/terraform/stacks/acm-general/import.tf
Import acmuic.azurecr.io container registry
=> 🚛 import container registry

kubernetes/argocd/stacks/common/vault-secrets-operator.yml, kubernetes/argocd/stacks/vault-secrets-operator/values.yml, kubernetes/argocd/stacks/vault-secrets-operator/vault-secrets-operator.yml
Installing the Vault Secrets Operator to allow secrets to be created with Vault secrets.
=> 💽 Installing the Vault Secrets Operator

kubernetes/argocd/stacks/common/projects.yml
Adding source repo to infra project to allow Hashicorp's Vault Secrets Operator to deploy.
=> 🙈 Adding source repo to infra project

kubernetes/argocd/stacks/vault-secrets-operator/values.yml
Fixing values.yml to reflect vault-secrets-operator expected values
=> 🔨 Fixing values.yml to reflect vault-secrets-operator values schema

kubernetes/argocd/stacks/vault-secrets-operator/values.yml
=> ⛏️ Fixing address protocol

kubernetes/argocd/stacks/vault-secrets-operator/values.yml
Adding role to vault secrets operator deployment
=> 🪄 Adding vault secrets operator role

kubernetes/argocd/stacks/common/umpf.yml, kubernetes/argocd/stacks/typesense/typesense.yml, kubernetes/argocd/stacks/umpf/umpf.yml, kubernetes/argocd/stacks/vault-secrets-operator/values.yml, kubernetes/argocd/stacks/vault-secrets-operator/vault-secrets-operator.yml
Add uber mega pathfinder stack
=> ✨ umpf-stack

kubernetes/argocd/stacks/umpf/umpf.yml
Noticed that umpf was crashing. Need more oomph.
=> 📈 more oomph for umpf

kubernetes/argocd/stacks/sparkhacks/sparkhacks-2023.yml, kubernetes/argocd/stacks/sparkhacks/sparkhacks-2024.yml, shell.nix
- New deployment for container
- New Service for deployment
- Point existing IngressRoute to new Service
NOT TESTED YET!
=> 🎇Add SparkHacks 2024

kubernetes/argocd/stacks/marketplace/marketplace.yml
Update IngressRoute rule to add admin dashboard for the Marketplace DB.
=> :jeans: Adding _ path for Pocketbase

kubernetes/argocd/stacks/sparkhacks/sparkhacks-2024.yml
I'm just fixing some things... don't mind me. 🙈
=> 🤦‍♂️ Fixing Deployment syntax for SparkHacks 2024

kubernetes/argocd/stacks/common/vault.yml
Update Vault-Helm from 0.25.0 to 0.28.1
=> Update Vault-Helm from 0.25.0 to 0.28.1

kubernetes/argocd/stacks/common/vault.yml
=> Revert "Update Vault-Helm from 0.25.0 to 0.28.1"

kubernetes/argocd/stacks/common/vault.yml
Reverts acm-uic/IaC#108
♻️ ♻️ ♻️
=> Revert "Revert "Update Vault-Helm from 0.25.0 to 0.28.1""

kubernetes/argocd/stacks/bmes-wordpress/certs.yml, kubernetes/argocd/stacks/bmes-wordpress/main.yml, kubernetes/argocd/stacks/common/bmes-wordpress.yml, kubernetes/argocd/stacks/common/projects.yml, kubernetes/argocd/stacks/traefik/values.yml
- Add BMES website https://convergehealth.cc
- Revert #95 to allow cert-manager to work again
- Deploy wordpress for BMES.
- ???
- Profit
=> 🧑‍⚕️Add wordpress for BMES.

proxmox/terraform/stacks/maid-cafe-k8s/k8s-01.tf
Removing clone.
Ensuring VM state is not started automatically.
=> 🤵 Maid Café - Kubernetes Cluster #3

.github/workflows/onprem_cafe_terraform_apply.yml, proxmox/terraform/stacks/maid-cafe-k8s/k8s-01.tf, proxmox/terraform/stacks/maid-cafe-k8s/k8s-02.tf, proxmox/terraform/stacks/maid-cafe-k8s/k8s-03.tf, proxmox/terraform/stacks/maid-cafe-k8s/k8s-04.tf, proxmox/terraform/stacks/maid-cafe-k8s/k8s-05.tf, proxmox/terraform/stacks/maid-cafe-k8s/k8s-06.tf, proxmox/terraform/stacks/maid-cafe-k8s/k8s-07.tf, proxmox/terraform/stacks/maid-cafe-k8s/k8s-08.tf
- Removing extended timeouts
- Adding the ability to manually run the apply on the onprem workflow
=> 🤵Maid Café - Kubernetes Cluster 5

kubernetes/argocd/maid-cafe-stacks/appsets/argo.yml, kubernetes/argocd/maid-cafe-stacks/appsets/pr-preview.yml, kubernetes/argocd/maid-cafe-stacks/helm_charts/argocd/values.yml, kubernetes/argocd/maid-cafe-stacks/iac.yml
Adding ArgoCD to manage itself
=> ⛏️ Adding helm management of ArgoCD using an ApplicationSet
