acm-uic/IaC

- helm_charts/jira/.helmignore
- helm_charts/jira/Chart.yaml
- helm_charts/jira/templates/NOTES.txt
- helm_charts/jira/templates/_helpers.tpl
- helm_charts/jira/templates/deployment.yaml
- helm_charts/jira/templates/ingress.yaml
- helm_charts/jira/templates/pvc.yaml
- helm_charts/jira/templates/service.yaml
- helm_charts/jira/templates/serviceaccount.yaml
- helm_charts/jira/values.yaml
First commit for Jira Helm Chart. This is my first stab at creating the Jira helm chart for automatic deployments and updates.  I noticed that this last week, we manually deployed Jira. While this is fine, it'll cause more pain in the future when we need to provide updates to Jira and other software.
Making use of Helm 3 will allow us to deploy code to the cluster in an automated fashion with Helm as the "package manager" of sorts.
* This was tested with a local Kubernetes cluster using the internal H2 database.
* Need to create another chart for the DB.
* Need to create automation to deploy corresponding charts. (Terraform?)
* Need to create automation to create DB secrets to be shared between namespaces.
> 📃 Jira Helm Chart 🧩

- azure/terraform/stacks/acm-general/dns.tf
This PR adds a DNS entry for flourishconf.acmuic.org. This will be a friendly name that will point to a Docker box, hosting the Flourish! 2023 website.
Relates to #18 .
> 🌐 Adding DNS entry for flourishconf.acmuic.org

- azure/terraform/stacks/acm-general/configuration/prod.tfvars
- azure/terraform/stacks/acm-general/service_principal.tf
- azure/terraform/stacks/acm-general/variables.tf
This PR allows Terraform to specify additional owner ids for usage on CI/CD-created resources (where applicable).
> Allowing the addition of statically-set owner ids

- azure/terraform/stacks/acm-general/service_principal.tf
Associating the application password with the application, rather than the service principal for visibility.
> Using application password instead of service principal password

- azure/terraform/stacks/acm-general/configuration/prod.tfvars
- azure/terraform/stacks/acm-general/service_principal.tf
- azure/terraform/stacks/acm-general/variables.tf
Adding `Reader` and `DNS Contributor` permissions to the service account.
> Adding additional permissions for the demo service account

- kubernetes/argocd/stacks/common/metallb.yml
This PR installs MetalLB on the Kubernetes cluster. This also specifies the IP pool range to be used by the load balancer.
> 🪙 Feature/Metallb

- kubernetes/argocd/stacks/common/argo_repos.yml
- kubernetes/argocd/stacks/common/metallb.yml
- kubernetes/terraform/stacks/1_k8s_cluster_setup/README.md
- kubernetes/terraform/stacks/1_k8s_cluster_setup/argo_config.tf
- kubernetes/terraform/stacks/1_k8s_cluster_setup/variables.tf
This PR defines repositories used within ArgoCD for future Helm deployments. This also sets up an application within ArgoCD to start configuring the cluster based on configuration located in `kuberetes/argocd/stacks/common`.
No automation is running this Terraform currently, so it is currently being manually run on an adhoc basis. This will change later once we install Github runners onto the cluster.
> 📔 Feature/ArgoCD Configuration

- kubernetes/argocd/stacks/common/metallb.yml
This PR updates the namespace for MetalLB.
Since MetalLB is dealing with the L2 network layer, it requires additional permissions to advertise the IP addresses it will be managing. By adding pod security labels, we allow privileged containers to run within the namespace.
The original error message during deployment is as follows:
From the daemonset-controller:
```
Error creating: pods "metallb-speaker-cqkt6" is forbidden: violates PodSecurity "baseline:latest": non-default capabilities (container "metallb-speaker" must not include "NET_ADMIN", "NET_RAW", "SYS_ADMIN" in securityContext.capabilities.add), host namespaces (hostNetwork=true), hostPort (container "metallb-speaker" uses hostPort 7472)
```
> 👮 bug/MetalLB Pod Security

- kubernetes/argocd/stacks/common/argo_repos.yml
- kubernetes/argocd/stacks/common/traefik.yml
This PR installs Traefik on the Kubernetes cluster.
This provides ingress support for other services.
In general, we can use the `IngressRoute` CRD to specify routing information for a given service. (See here for more info: https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroute)
> 🚦 Feature/Traefik

- kubernetes/argocd/stacks/common/argo_repos.yml
- kubernetes/argocd/stacks/common/hostpath-provisioner.yml
- kubernetes/argocd/stacks/common/mayastor.yml
- kubernetes/argocd/stacks/common/metallb.yml
- kubernetes/argocd/stacks/common/traefik.yml
This PR installs [Mayastor](https://openebs.io/docs/concepts/mayastor), a distributed block storage data platform. This allows applications running on the cluster to have data replication and to allow rescheduling across nodes without replying on external servers.
As a dependency of Mayastor, a `hostpath` storage class and dynamic provisioner was added. (Helm chart: https://artifacthub.io/packages/helm/rimusz/hostpath-provisioner)
Additional storage devices have also been added to the worker nodes to accommodate the block storage data platform requirements. These additional storage devices are located on local hypervisor storage instead of on the acm-nfs.
- The initial provisioning of Mayastor requires a prior working storage class. By default, the cluster does not have this, so in …
> 💽 Feature/Mayastor

- kubernetes/argocd/stacks/common/vault-values-override.yml
- kubernetes/argocd/stacks/common/vault.yml
This fixes an issue with Vault not being able to communicate between nodes. Also switching to passing external traffic through Traefik to ensure the internal certificates aren't being exposed. This may need additional work to make ingress -> service communication work.
> 🐛 Bug/Vault TLS

- azure/terraform/stacks/typesense/service_principal.tf
Update typesense federated credentials for github actions running on main branch of acm-uic/acm-uic.github.io
Error:
```
Error: : AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://token.actions.githubusercontent.com/'. Assertion Subject: 'repo:acm-uic/acm-uic.github.io:ref:refs/heads/main'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation
```
> update typesense federated creds subject for main branch

- kubernetes/argocd/stacks/common/argo_repos.yml
- kubernetes/argocd/stacks/common/cert-manager/cert-issuers.yml
- kubernetes/argocd/stacks/common/cert-manager/cert-manager.crds.yaml
- kubernetes/argocd/stacks/common/cert-manager/cert-manager.yml
- kubernetes/argocd/stacks/common/cert-manager/self-ca.yml
Add Cert Manager via helm chart.
Notes:
- Letsnecrypt acquisition has not been tested
- Can test once external firewall punchthrough is done
- Custom Resource Definitions are installed via YAML file as helm wasnt installing them
Cluster Issuers:
- letsencrypt-prod (real letsencrypt)
- letsencrypt staging (for testing)
- acmuic-self-ca (Self rolled CA for internal usage)
> Add ❇cert-manager❇

- kubernetes/argocd/stacks/common/cert-manager/self-ca.yml
This PR updates the self-signed CA with a different allowed usage policy.
Originally, our CA had the following usages:
<details><summary>See full cert description (click here)</summary>
<code>
$ openssl x509 -in ~/Downloads/acm-ca.crt -text -noout
Certificate:
Data:
Version: 3 (0x2)
Serial Number:
66:64:7b:af:b1:18:4a:1d:52:44:70:04:46:d0:31:34
Signature Algorithm: ecdsa-with-SHA256
Issuer: CN = acmuic-self-ca
Validity
Not Before: Jul 26 17:30:14 2023 GMT
Not After : Jul 23 17:30:14 2033 GMT
Subject: CN = acmuic-self-ca
Subject Public Key Info:
Public Key Algorithm: id-ecPublicKey
Public-Key: (256 bit)
pub:
04:e2:18:87:7d:bb:fd:6f:62:d0:20:0d:c2:6a:d1:
d4:ee:c3:71:69:d1:72:d7:cd:18:db:74:9f:d3:e4:
67:d7:29:e3:76:99:41:ac:e4:99:a1:74:0c:16:bf:
f3:e2:f6:f1:59:5a:24:9a:b6:21:69:c5:f2:53:da: …
> 🐞 Bug/trust-issues: Updating the allowed usage of the CA

- kubernetes/terraform/stacks/1_k8s_cluster_setup/argocd.tf
- kubernetes/terraform/stacks/1_k8s_cluster_setup/configurations/acmapp_prod.tfvars
This upgrades ArgoCD to 2.7.9. Previous version was 2.7.7.
Release Notes: 
- https://github.com/argoproj/argo-cd/releases/tag/v2.7.9
- https://github.com/argoproj/argo-cd/releases/tag/v2.7.8
> ⬆️ Feature/ArgoCD-upgrade-2.7.9: Upgrading ArgoCD to 2.7.9

- kubernetes/argocd/stacks/common/traefik.yml
- kubernetes/argocd/stacks/common/vault-values-override.yml
- kubernetes/argocd/stacks/common/vault.yml
- This PR updates the certificate used by Vault nodes. The certificate is now generated by `cert-manager`. 
- This initially self-signed certificate is used for inter-pod communication.
- This also updates the Traefik ingress to correctly use these certificates for TLS terminate between the ingress and the vault service. (We were previously getting bad handshake errors because the ingress client did not trust the self-signed ca.)
> 🔒Feature/vault certs

- kubernetes/terraform/stacks/1_k8s_cluster_setup/configurations/acmapp_prod.tfvars
This upgrades ArgoCD to 2.8.0. Previous version was 2.7.9.
Release Notes:
- https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.7-2.8/
- https://github.com/argoproj/argo-cd/releases/tag/v2.8.0
- https://github.com/argoproj/argo-cd/releases/tag/v2.7.9
> ⬆️ Feature/ArgoCD-upgrade-2.8.0: Upgrading ArgoCD to 2.8.0

- azure/terraform/stacks/vault-injector/.terraform.lock.hcl
- azure/terraform/stacks/vault-injector/README.md
- azure/terraform/stacks/vault-injector/backend.tf
- azure/terraform/stacks/vault-injector/external_dns.tf
- azure/terraform/stacks/vault-injector/main.tf
- azure/terraform/stacks/vault-injector/providers.tf
This new Terraform stack will place outputs created by Terraform into a given Vault instance.
Automation for this pipeline has NOT been written yet, so manual applies need to be run for this stack for now. Once we have a Github Actions worker that can access the Vault address directly, we can setup additional automation for this to run when changes are applied.
> 💉 Feature/Azure-Vault-injector

- azure/terraform/stacks/acm-general/external-dns.tf
- azure/terraform/stacks/acm-general/variables.tf
- azure/terraform/stacks/vault-injector/external_dns.tf
- azure/terraform/stacks/vault-injector/main.tf
- azure/terraform/stacks/vault-injector/providers.tf
- kubernetes/argocd/stacks/common/argo_repos.yml
- kubernetes/argocd/stacks/common/externaldns.yml
- kubernetes/argocd/stacks/common/helm-values/externaldns-values.yml
- kubernetes/argocd/stacks/common/vault-values-override.yml
- kubernetes/argocd/stacks/common/vault.yml
This installs and configures ExternalDNS on the Kubernetes cluster.
Changes were made to the Terraform stacks to:
- Output the created ExternalDNS information
- Inject the configuration data into Vault
Notable changes to the default ExternalDNS helm chart:
- The Vault injector was used to place credentials into the container dynamically via a sidecar
- Annotations were added to the pod definition to allow the Vault Injector to do its work
- A dummy certificate(`externaldns-vault-cert`) was generated to allow the vault-injector access to the Vault endpoint. Using a dummy cert allows us to not expose key information from the Vault/cert-manager namespace.
Notable changes to the Vault deployment:
- The main Vault certificate was updated to accommodate internal service traffic between …
> 🌐 Feature/Externaldns

- .github/workflows/azure_terraform_apply.yml
- .github/workflows/azure_terraform_plan.yml
- azure/README.md
Using federated auth instead of client secrets to avoid having to deal with renewing secrets.
Made updates to the AAD application to add the federated credentials for pull requests, and main branch.
> Use AAD federated auth for azure login

- kubernetes/argocd/stacks/common/argocd.yml
- kubernetes/argocd/stacks/common/ingress-forwarder.yml
remove unnecessary "name: ''" from helm argocd applications
"iac" application goes out of sync with this diff:
> 🧹 remove unnecessary "name: ''" from helm argocd applications

- kubernetes/argocd/stacks/common/projects.yml
- kubernetes/argocd/stacks/common/sparkhacks.yml
- kubernetes/argocd/stacks/ingress-forwarder/ingress-forwarder.yml
- kubernetes/argocd/stacks/sparkhacks/certs.yml
- kubernetes/argocd/stacks/sparkhacks/sparkhacks-2023.yml
This PR adds the SparkHacks 2023 site to the Kubernetes cluster.
Note the https://github.com/acm-uic/sparkhacks-2023/pull/235 creates the container being used here.
Additional work:
- Removes the external service referencing the `docker2` server
- Issues the Let's Encrypt certificate for all of `sparkhacksatuic.com`
- Creates a `sparkhacks` project within ArgoCD to organize apps.
> ✨ Moving Sparkhacks 2023 site to Kubernetes

- kubernetes/argocd/stacks/common/argo_repos.yml
- kubernetes/argocd/stacks/common/keel.yml
- kubernetes/argocd/stacks/sparkhacks/sparkhacks-2024.yml
Auto update mechanism to refresh containers for sparkhacks
> 🇰Add keel.sh

- kubernetes/argocd/stacks/common/k8s-oidc.yml
- kubernetes/argocd/stacks/workload-identity/openid-configuration-serve.yml
This manifest adds a `nginx` container that serves the following
jwks: https://k8s-oidc.acmuic.org/openid/v1/jwks
openid-configuration: https://k8s-oidc.acmuic.org/.well-known/openid-configuration
The files to serve are obtained by an init container which gets the jwks, openid-configuration from the api server via `kubectl`
Changed made in machine config:
- Add args to api server with the new issuer
- Generate new RSA key to be use for service account token signing
Keys generated and applied with this script
```bash
#!/bin/bash
set -v
TALOSCONFIG=./k8s-talosconfig
KUBECONFIG=./k8s-kubeconfig
ISSUER=https://k8s-oidc.acmuic.org
JWKS_URI=https://k8s-oidc.acmuic.org/openid/v1/jwks
RSA_KEY=$(openssl genrsa 4096 2> /dev/null | openssl pkey -traditional)
RSA_KEY_ENCODED=$(echo "${RSA_KEY}" | …
```
> Serve openid configuration and public key used for service account token signing to enable support for workload identity

- kubernetes/argocd/stacks/common/projects.yml
Fix error: `application repo https://azure.github.io/azure-workload-identity/charts is not permitted in project 'infrastructure'`
> 💪🏽 allow repo https://azure.github.io/azure-workload-identity/charts in infrastructure project

- kubernetes/argocd/stacks/common/vault-values-override.yml
Use workload identity to get unseal secrets from azure keyvault
> Auto unseal vault with Azure KeyVault

- proxmox/terraform/stacks/maid-cafe-k8s/k8s-02.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-03.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-04.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-05.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-06.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-07.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-08.tf
- proxmox/terraform/stacks/maid-cafe-k8s/outputs.tf
Adding VMs to Kubernetes pool. Adding the rest of the control plane and worker VMs.
> 🤵 Maid Café - Kubernetes Cluster VMs

- proxmox/terraform/stacks/maid-cafe-k8s/k8s-01.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-02.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-03.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-04.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-05.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-06.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-07.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-08.tf
Ignoring VM state after initial creation.
With this PR, this should be all that is needed for the initial VM creation.
> 🤵Maid Café - Kubernetes Cluster 6

- kubernetes/argocd/maid-cafe-stacks/IaC.yml
- kubernetes/argocd/maid-cafe-stacks/appsets/pr-preview.yml
- kubernetes/argocd/maid-cafe-stacks/iac.yml
Adding basic configuration for new K8s cluster.
> 🤵New configuration for Maid Café cluster boilerplate

- proxmox/terraform/stacks/maid-cafe-k8s/k8s-01.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-02.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-03.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-04.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-05.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-06.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-07.tf
- proxmox/terraform/stacks/maid-cafe-k8s/k8s-08.tf
Bumping image used for K8s VMs. Tagging all VMs with VLAN 9.
> 🤵Maid Café - Kubernetes Cluster 7

- kubernetes/argocd/stacks/common/vaultwarden.yml
- kubernetes/argocd/stacks/vaultwarden/vaultwarden.yml
Uses the simplified single vaultwarden docker container. Fixes #62.
> Setup Vaultwarden on Kubernetes cluster
